default_agent: wecareinternalagent_Agent
agents:
  wecareinternalagent_Agent:
    name: wecareinternalagent_Agent
    entrypoint: C:\Users\Manish\Desktop\base\wecareinternalagent\src\main.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_10
    platform: linux/amd64
    container_runtime: null
    source_path: C:\Users\Manish\Desktop\base\wecareinternalagent\src
    aws:
      execution_role: arn:aws:iam::010526260063:role/base-wecare-digital-whatsapp-full-access-role
      execution_role_auto_create: false
      account: '010526260063'
      region: ap-south-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://dev.wecare.digital/Bedrock/agent-core
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: wecareinternalagent_Agent-9bq7z65aEP
      agent_arn: arn:aws:bedrock-agentcore:ap-south-1:010526260063:runtime/wecareinternalagent_Agent-9bq7z65aEP
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: true
